{% set name = "pycromanager" %}
{% set version = "0.28.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycromanager-{{ version }}.tar.gz
  sha256: de076c9cf99bb1a37508a5a85d241880e96b007e6a51c78cc3b9463f99d1b015
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask-core >=2022.2.0
    - docstring-inheritance
    - ndtiff >=2.2.0
    - numpy
    - python >=3.6
    - pyzmq

test:
  imports:
    - pycromanager
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pycromanager
  summary: Open source microscope control using python
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/micro-manager/pycro-manager

extra:
  recipe-maintainers:
    - goanpeca
    - henrypinkard
